#!/usr/bin/env bats
# -*- mode: sh -*-
source "tests/common.sh"

setup_file() {
    export OUTPUT_DIR=$(mktemp -d)
    local TEST_DIR=$PWD
    (cd "$OUTPUT_DIR"; stately manifest < "$TEST_DIR/tests/dhall-render-test.json")
}

teardown_file() {
    rm -rf "$OUTPUT_DIR"
}

@test "Staging files works" {
    stately -h
}

@test "Test file examples/generated/examples/files/config-list.yml in subdir was created" {
    test "$(file_type examples/generated/examples/files/config-list.yml)" = "regular file"
    local FILE_CONTENTS=$(cat<<"EOF"

# **NOTE**: this file is generated by `dhall-render`.
# You should NOT edit it manually, your changes will be lost.

age: 50
name: tim
---
age: 50
name: fred
EOF
)

    test "$(file_contents examples/generated/examples/files/config-list.yml)" = "$FILE_CONTENTS"
}

@test "Test file examples/generated/examples/files/config.json in a subdir was created" {
    test "$(file_type examples/generated/examples/files/config.json)" = "regular file"

    local FILE_CONTENTS=$(cat<<"EOF"
{
  "age": 100,
  "name": "tim"
}
EOF
          )

    test "$(file_contents examples/generated/examples/files/config.json)" = "$FILE_CONTENTS"
}

@test "Test file examples/generated/examples/files/config.yml in a subdir was created" {
    test "$(file_type examples/generated/examples/files/config.yml)" = "regular file"

    local FILE_CONTENTS=$(cat<<"EOF"

# **NOTE**: this file is generated by `dhall-render`.
# You should NOT edit it manually, your changes will be lost.

age: 100
name: tim
EOF
          )

    test "$(file_contents examples/generated/examples/files/config.yml)" = "$FILE_CONTENTS"
}

@test "Test file examples/generated/examples/files/hello in a subdir was created" {
    test "$(file_type examples/generated/examples/files/hello)" = "regular file"

    local FILE_CONTENTS=$(cat<<"EOF"

# **NOTE**: this file is generated by `dhall-render`.
# You should NOT edit it manually, your changes will be lost.

Hello!
EOF
          )

    test "$(file_contents examples/generated/examples/files/hello)" = "$FILE_CONTENTS"
}

@test "Test file examples/generated/examples/files/hello.sh in a subdir was created" {
    test "$(file_type examples/generated/examples/files/hello.sh)" = "regular file"

    local FILE_CONTENTS=$(cat<<"EOF"

# **NOTE**: this file is generated by `dhall-render`.
# You should NOT edit it manually, your changes will be lost.

echo 'Hello!'
EOF
          )

    test "$(file_contents examples/generated/examples/files/hello.sh)" = "$FILE_CONTENTS"
}

@test "Test file examples/generated/examples/files/hello.sh is executable" {
    mode=$(stat -c "%a" "$OUTPUT_DIR/examples/generated/examples/files/hello.sh")
    [ "$mode" = "755" ]
}

@test "Test file foo in a subdir was created 1" {
    test "$(file_type examples/generated/examples/files/list/1.yml)" = "regular file"
}

@test "Test file foo in a subdir was created 2" {
    test "$(file_type examples/generated/examples/files/list/2.yml)" = "regular file"
}

@test "Test file foo in a subdir was created 3" {
    test "$(file_type examples/generated/examples/files/list/3.yml)" = "regular file"
}
